#!/bin/bash

set -o errexit
set -o xtrace

export DOCKER_CLI_EXPERIMENTAL=enabled

builddir="/srv/jellyfin"
reponame="jellyfin"
repotype="server"

docker_image="jellyfin/jellyfin"

pushd ${builddir}

# Grab the source and init
./build ${reponame} --clone-only

pushd projects/${repotype}/${reponame}

build_manifests="n"
tagname="$( hub release -L1 )"

for arg in ${@}; do
case "${arg}" in
    tag-name=*)
        tagname_value="$( awk -F'=' '{ print $NF }' <<<"${arg}" )"
        case "$tagname_value" in
            # Specific version
            v*)
                tagname=${tagname_value}
            ;;
            # Latest, or junk data
            *)
                # This was set earlier
                continue
            ;;
        esac
    ;;
    build-docker-manifests=yes)
        build_manifests="y"
    ;;
    *)
        continue
    ;;
esac
done

#####

nice_tagname="$( sed 's/^v//g' <<<"${tagname}" )"

# Check out the tag
git tag -d tags/${tagname} || true
git fetch --all
git checkout tags/${tagname}

# Initialize the submodule
git submodule update --init

# Set up qemu static
docker run --rm --privileged multiarch/qemu-user-static:register --reset

# Build images (amd64, arm, arm64)
docker build --no-cache --pull -f Dockerfile -t "${docker_image}":${nice_tagname}-amd64 . &>${curdir}/../../logs/build-test/docker-amd64.log
docker build --no-cache --pull -f Dockerfile.arm -t "${docker_image}":${nice_tagname}-arm . &>${curdir}/../../logs/build-test/docker-arm.log
docker build --no-cache --pull -f Dockerfile.arm64 -t "${docker_image}":${nice_tagname}-arm64 . &>${curdir}/../../logs/build-test/docker-arm64.log

# Push images (amd64, arm, arm64)
docker push "${docker_image}":${nice_tagname}-amd64
docker push "${docker_image}":${nice_tagname}-arm
docker push "${docker_image}":${nice_tagname}-arm64

if [[ ${build_manifests} == 'y' ]]; then
# Create tagname manifest
docker manifest create --amend "${docker_image}:${nice_tagname}" \
	"${docker_image}:${nice_tagname}-amd64" \
	"${docker_image}:${nice_tagname}-arm" \
	"${docker_image}:${nice_tagname}-arm64"
docker manifest push --purge "${docker_image}:${nice_tagname}"

# Create latest manifest
docker manifest create --amend "${docker_image}:latest" \
	"${docker_image}:${nice_tagname}-amd64" \
	"${docker_image}:${nice_tagname}-arm" \
	"${docker_image}:${nice_tagname}-arm64"
docker manifest push --purge "${docker_image}:latest"
fi

#####

popd

docker image rm -f $( docker images -aq ) || true
