#!/bin/bash

set -o errexit
set -o xtrace

tagname="${1}"

builddir="/srv/jellyfin"
reponame="jellyfin"
repotype="server"

reposerver="repo1.jellyfin.org"

echo "*** PREPARING REPOSITORY ***"
pushd ${builddir}

# Grab the source and init
./build ${reponame} --clone-only

pushd projects/${repotype}/${reponame}

git reset --hard HEAD
git clean -fd

# Check out the tag
git tag -d tags/${tagname} || true
git fetch --all
git checkout tags/${tagname}

# Initialize the submodule
git submodule update --init

# Perform nuget restore
dotnet restore --no-cache

popd

echo "*** BUILDING NUGET PACKAGES ***"
/bin/bash ${builddir}/scripts/build.d/build-jellyfin-nuget

echo "*** BUILDING DOCKER IMAGES ***"
/bin/bash ${builddir}/scripts/build.d/build-jellyfin-docker tag-name=${tagname} build-docker-manifests=yes

echo "*** BUILDING OS PACKAGES ***"
./build ${reponame}

echo "*** SYNCING OS PACKAGES TO REPO ***"
rsync -avz bin/${reponame}/ build@${reposerver}:/srv/incoming/${reponame}_${tagname}

echo "*** COLLECTING PACKAGES FOR REPO ***"
ssh build@${reposerver} "sudo /srv/collect-server.sh /srv/incoming/${reponame}_${tagname}"

echo "*** UPLOADING BINARIES TO GITHUB RELEASE ***"
for dir in bin/${reponame}/*; do
    artifact_dir="$( awk -F'/' '{ print $NF }' <<<"${dir}" )"
    temp_dir="$( mktemp -d )"
    pushd ${dir}
    case ${artifact_dir} in
        debian-package-*)
            mmv "jellyfin_*_*.deb" "${temp_dir}/jellyfin_#1_debian-#2.deb"
            mmv "jellyfin_*_*.buildinfo" "${temp_dir}/jellyfin_#1_debian-#2.buildinfo" || true
        ;;  
        ubuntu-package-*)
            mmv "jellyfin_*_*.deb" "${temp_dir}/jellyfin_#1_ubuntu-#2.deb"
            mmv "jellyfin_*_*.buildinfo" "${temp_dir}/jellyfin_#1_ubuntu-#2.buildinfo" || true
        ;;  
        fedora-package-*|centos-package-*)
            rm *.src.rpm
            mv *.rpm "${temp_dir}/"
        ;;  
        linux-x64)
            mmv "jellyfin_*.portable.tar.gz" "${temp_dir}/jellyfin_#1_linux-amd64.tar.gz"
        ;;  
        macos)
            mmv "jellyfin_*.portable.tar.gz" "${temp_dir}/jellyfin_#1_macos.tar.gz"
        ;;  
        portable)
            mmv "jellyfin_*.portable.tar.gz" "${temp_dir}/jellyfin_#1_portable.tar.gz"
        ;;  
        win-x64)
            mmv "jellyfin_*.zip" "${temp_dir}/jellyfin_#1_windows-x64.zip"
        ;;  
        win-x86)
            mmv "jellyfin_*.zip" "${temp_dir}/jellyfin_#1_windows-x86.zip"
        ;;
    esac
    # Upload the artifacts to the GitHub release
    for artifact in ${temp_dir}/*; do
        /bin/bash ${builddir}/scripts/upload-artifact "${reponame}" "${tagname}" "${artifact}"
    done
    popd
    rm -r ${temp_dir}
done

echo "*** CLEANING UP ***"
rm -r ${builddir}/bin/jellyfin
popd
docker image ls | awk '{ print $3 }' | xargs docker image rm --force || true
exit 0
