#!/bin/bash

set -o errexit
set -o xtrace

reponame="${1}"
tagname="${2}"

builddir="/srv/jellyfin"
repodir="/srv/repository"
repotype="plugin"

pushd ${builddir}

# Grab the source and init
./build ${reponame} --clone-only

pushd projects/${repotype}/${reponame}

# Check out the tag
git tag -d tags/${tagname} || true
git fetch --all
git checkout tags/${tagname}

# Initialize the submodule
git submodule update --init

popd

${builddir}/build-plugin.sh ${builddir}/projects/${repotype}/${reponame}

# Clean up
popd
exit 0
